const addCourseFormActionTypes = {
    CHANGE_NAME_STATE: 'CHANGE_NAME_STATE',
    CHANGE_START_DATE_STATE: 'CHANGE_START_DATE_STATE',
    CHANGE_END_DATE_STATE:"CHANGE_END_DATE_STATE",
    CHANGE_WEEKLY_WINDOWS_STATE:"CHANGE_WEEKLY_WINDOWS_STATE",
    ADD_NEW_WEEKLY_WINDOW:"ADD_NEW_WEEKLY_WINDOW",
    DELETE_WEEKLY_WINDOW:"DELETE_WEEKLY_WINDOW",
}

export default addCourseFormActionTypes;