export const addStudentFormActionTypes = {
    CHANGE_NAME_STATE:"CHANGE_NAME_STATE",
    CHANGE_EMAIL_STATE:"CHANGE_EMAIL_STATE",
    CHANGE_ADDRESS_STATE:"CHANGE_ADDRESS_STATE",
    CHANGE_PHONE_STATE:"CHANGE_PHONE_STATE",
}